BASE_PATH = '../../data/Ground Truth/'

# DataCleaner.py
READ_FROM_FILE_PRE_OCR = True
READ_FROM_FILE_INTERMEDIATES = True
WRITE_FILE_PRE_OCR = True
SAVE_PATH_PRE_OCR = BASE_PATH + "dataframes/PRE_OCR"
SAVE_PATH_17THCENTURYNEWSPAPER = BASE_PATH + "dataframes/17THCENTURYNEWSPAPER"
SAVE_PATH_HISTORICALNEWSPAPERS = BASE_PATH + "dataframes/HISTORICALNEWSPAPER"
SAVE_PATH_DBNL_BOOKS = BASE_PATH + "dataframes/DBNL_BOOKS"

# DataCreator.py
MAX_THREADING_COUNT = 20
READ_FROM_FILE_POST_OCR = True
WRITE_FILE_POST_OCR = True
SAVE_PATH_POST_OCR = BASE_PATH + "dataframes/POST_OCR"

# ImageCreation.py
IMAGE_PATH_BLANK = "../images/templates/white.jpg"
IMAGE_WRITE_BLANK = "../images/run/white-edited-"

# Telegram

TELEGRAM_TOKEN = "6148002997:AAGOq31lNenxEf9PvFWsNTHcf6t7UcoUsZ8"
TELEGRAM_CHAT_ID = "6198204545"